### ISSUE TITLE
Add "console" feature

### ISSUE THREAD

**Issue by JonathanFager** [BryggansBryggeri/bryggui#7]
Is there a need for something like a console feature, where the user can get some more information?

**Comment by JonathanFager** [comment]
Is this needed @jackonelli ? If not, close

**Comment by jackonelli** [comment]
I'm not sure what you mean by it.
I want a sep. 'error view' in the absence of a supervisor connection, see #13 
Don't know how it relates to this.

**Comment by JonathanFager** [comment]
I was thinking of basically having a pane or something that shows NATS-messages, browser console and all these things. Might be tricky to implement, and would also only be needed if we screw up. So no, I dont think this is needed.
